name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"
      - name: Install dependencies
        run: npm install
      - name: Tests unidade
        run: npm test tests/unidade.test.js
      - name: Tests integracao
        run: npm test tests/integracao.test.js
